[project]
name = "masala_blender"
version = "0.0.1"
description = "Modular asset creation framework based on AssetBlocks"
readme = "README.md"
authors = [
    { name = "Tristan Languebien", email = "tristan.languebien@bigcompany.fr" }
]
requires-python = "==3.13.9"
dependencies = [
    "masala",
]

[project.optional-dependencies]
dev = [
    "fake-bpy-module-latest",
    "pip>=26.0.1"
]

docs = [
    "zensical",
    "mkdocstrings-python"
]

[tool.uv.sources]
masala = { path = "../masala", editable = true }
