[project]
name = "masala_blender"
version = "0.0.1"
description = "Modular asset creation framework based on AssetBlocks"
readme = "README.md"
authors = [
    { name = "Tristan Languebien", email = "tristan.languebien@bigcompany.fr" }
]
requires-python = "==3.13.9"
dependencies = [
    "fake-bpy-module-latest",
    "lucent-codex",
    "PySide6",
    "QtPy",
    "QtAwesome",
    "NodeGraphQt",
    "setuptools",
    "pip>=26.0.1"
]
